server:
  port: 8091
spring:
  application:
    name: ahmniue-manage
  profiles:
    active: dev #默认为开发环境
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: ahmniue-secret #JWT加解密使用的密钥
  expiration: 3600 #JWT的超期限时间(60*60)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

redis:
  database: ahmniue
  key:
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
  expire:
    common: 86400 #1小时

tencent:
  secretId: AKID3OssbvlvgIi7JE861iEestfd185wsjjT
  secretKey: P1PYWO1NU0rRlslqgFkfMn13dy5q674D
  region: ap-shanghai
  bucketName: ahmniue-1257961979
  path: https://ahmniue-1257961979.cos.ap-shanghai.myqcloud.com
  prefix: ahmniue_admin/images/

secure:
  ignored:
    urls: #安全路径白名单
      - /** #全部权限放行
#      - /swagger-ui.html
#      - /swagger-resources/**
#      - /swagger/**
#      - /**/v2/api-docs
#      - /**/*.js
#      - /**/*.css
#      - /**/*.png
#      - /**/*.ico
#      - /webjars/springfox-swagger-ui/**
#      - /actuator/**
#      - /druid/**
#      - /admin/login
#      - /admin/register
#      - /admin/info
#      - /admin/logout
